#!/bin/bash
set -eu

if [ -z "${__MATRIXOS_ENV_PARSED:-}" ]; then

# The "special var".
DEFAULT_MATRIXOS_DEV_DIR=/matrixos
MATRIXOS_DEV_DIR=${MATRIXOS_DEV_DIR:-"${DEFAULT_MATRIXOS_DEV_DIR}"}

source "${MATRIXOS_DEV_DIR}"/lib/env_lib.sh

# Re-initialize MATRIXOS_DEV_DIR from config.
MATRIXOS_DEV_DIR=$(env_lib.get_root "${MATRIXOS_DEV_DIR}")

# Directory used for file locks, to synchronize operations of various kind.
MATRIXOS_LOCKS_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "matrixOS" "LocksDir")
# Directory used for various log files that can be generated by seeders, releasers, imagers.
MATRIXOS_LOGS_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "matrixOS" "LogsDir")

# Name of the os.
MATRIXOS_OSNAME=$(env_lib.get_simple_var "matrixOS" "OsName")
MATRIXOS_FANCY_OSNAME=$(env_lib.get_simple_var "matrixOS" "FancyOsName")
MATRIXOS_ARCH=$(env_lib.get_simple_var "matrixOS" "Arch")

# matrixOS Git repos URLs and paths.
MATRIXOS_OVERLAY_GIT_REPO=$(env_lib.get_simple_var "matrixOS" "OverlayGitRepo")
MATRIXOS_PRIVATE_EXAMPLE_GIT_REPO=$(env_lib.get_simple_var "matrixOS" "PrivateExampleGitRepo")
MATRIXOS_PRIVATE_GIT_REPO_PATH=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "matrixOS" "PrivateGitRepoPath")
MATRIXOS_DEFAULT_PRIVATE_GIT_REPO_PATH=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "matrixOS" "DefaultPrivateGitRepoPath")
MATRIXOS_GIT_REPO=$(env_lib.get_simple_var "matrixOS" "GitRepo")
MATRIXOS_DEFAULT_USERNAME=$(env_lib.get_simple_var "matrixOS" "DefaultUsername")

# OSTree releasing and pulling.
MATRIXOS_OSTREE_REPO_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Ostree" "RepoDir")
MATRIXOS_OSTREE_REMOTE=$(env_lib.get_simple_var "Ostree" "Remote")
MATRIXOS_OSTREE_REMOTE_URL=$(env_lib.get_simple_var "Ostree" "RemoteUrl")
MATRIXOS_OSTREE_COLLECTION_ID=$(env_lib.get_simple_var "Ostree" "CollectionId")
MATRIXOS_OSTREE_KEEP_OBJECTS_YOUNGER_THAN=$(env_lib.get_simple_var "Ostree" "KeepObjectsYoungerThan")
MATRIXOS_OSTREE_FULL_SUFFIX=$(env_lib.get_simple_var "Ostree" "FullBranchSuffix")

## Seeders section
MATRIXOS_SEEDER_DOWNLOADS_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Seeder" "DownloadsDir")
MATRIXOS_SEEDER_DISTFILES_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Seeder" "DistfilesDir")
MATRIXOS_SEEDER_BINPKGS_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Seeder" "BinpkgsDir")
MATRIXOS_SEEDER_PORTAGE_REPOS_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Seeder" "PortageReposDir")
MATRIXOS_SEEDER_GPG_KEYS_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Seeder" "GpgKeysDir")

# OSTree GPG Support.
MATRIXOS_OSTREE_GPG_ENABLED=$(env_lib.get_bool_var "Ostree" "Gpg" "true")
MATRIXOS_OSTREE_DEV_GPG_HOMEDIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Ostree" "DevGpgHomeDir")
MATRIXOS_OSTREE_OFFICIAL_GPG_PUB_PATH=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Ostree" "GpgOfficialPublicKey")

# /etc/matrixos-private derived configs.
MATRIXOS_OSTREE_GPG_KEY_PATH=$(env_lib.get_root_var "${MATRIXOS_PRIVATE_GIT_REPO_PATH}" "Ostree" "GpgPrivateKey")
MATRIXOS_OSTREE_GPG_PUB_PATH=$(env_lib.get_root_var "${MATRIXOS_PRIVATE_GIT_REPO_PATH}" "Ostree" "GpgPublicKey")

# These MUST be derived from the default path, because they are used inside chroots.
MATRIXOS_SECUREBOOT_KEY_PATH=$(env_lib.get_root_var "${MATRIXOS_DEFAULT_PRIVATE_GIT_REPO_PATH}" "Seeder" "SecureBootPrivateKey")
MATRIXOS_SECUREBOOT_CERT_PATH=$(env_lib.get_root_var "${MATRIXOS_DEFAULT_PRIVATE_GIT_REPO_PATH}" "Seeder" "SecureBootPublicKey")
MATRIXOS_JAILBROKEN_BOOT_LOADER_ENTRY=$(env_lib.get_simple_var "Jailbreak" "BootLoaderEntry")

MATRIXOS_RO_VDB=$(env_lib.get_simple_var "Releaser" "ReadOnlyVdb")
MATRIXOS_OSTREE_SYSROOT=$(env_lib.get_simple_var "Ostree" "Sysroot")
MATRIXOS_BOOT_ROOT=$(env_lib.get_simple_var "Imager" "BootRoot")
MATRIXOS_EFI_ROOT=$(env_lib.get_simple_var "Imager" "EfiRoot")
MATRIXOS_RELATIVE_EFI_BOOT_PATH=$(env_lib.get_simple_var "Imager" "RelativeEfiBootPath")
MATRIXOS_BOOT_EFI_EXECUTABLE=$(env_lib.get_simple_var "Imager" "EfiExecutable")
MATRIXOS_EFI_CERT_FILE_NAME=$(env_lib.get_simple_var "Imager" "EfiCertificateFileName")
MATRIXOS_EFI_CERT_DER_FILE_NAME=$(env_lib.get_simple_var "Imager" "EfiCertificateFileNameDer")
MATRIXOS_EFI_CERT_KEK_FILE_NAME=$(env_lib.get_simple_var "Imager" "EfiCertificateFileNameKek")
MATRIXOS_EFI_CERT_KEK_DER_FILE_NAME=$(env_lib.get_simple_var "Imager" "EfiCertificateFileNameKekDer")

MATRIXOS_EFI_STANDARD_BOOT_EXECUTABLE_PATH=$(env_lib.get_simple_var "Imager" "EfiStandardBootExecutablePath")

__MATRIXOS_ENV_PARSED=1
fi