#!/bin/bash
set -eu

if [ -z "${__MATRIXOS_ENV_PARSED:-}" ]; then

# The "special var".
DEFAULT_MATRIXOS_DEV_DIR=/matrixos
MATRIXOS_DEV_DIR=${MATRIXOS_DEV_DIR:-"${DEFAULT_MATRIXOS_DEV_DIR}"}

source "${MATRIXOS_DEV_DIR}"/lib/env_lib.sh

# Re-initialize MATRIXOS_DEV_DIR from config.
MATRIXOS_DEV_DIR=$(env_lib.get_root "${MATRIXOS_DEV_DIR}")

# Directory used for file locks, to synchronize operations of various kind.
MATRIXOS_LOCKS_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "matrixOS" "LocksDir" "locks/")
# Directory used for various log files that can be generated by seeders, releasers, imagers.
MATRIXOS_LOGS_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "matrixOS" "LogsDir" "logs/")

# Name of the os.
MATRIXOS_OSNAME=$(env_lib.get_simple_var "matrixOS" "OsName" "matrixos")
MATRIXOS_FANCY_OSNAME=$(env_lib.get_simple_var "matrixOS" "FancyOsName" "matrixOS")
MATRIXOS_ARCH=$(env_lib.get_simple_var "matrixOS" "Arch" "amd64")

# matrixOS Git repos URLs and paths.
MATRIXOS_OVERLAY_GIT_REPO=$(env_lib.get_simple_var "matrixOS" "OverlayGitRepo" "https://github.com/lxnay/matrixos-overlay.git")
MATRIXOS_PRIVATE_EXAMPLE_GIT_REPO=$(env_lib.get_simple_var "matrixOS" "PrivateExampleGitRepo" "https://github.com/lxnay/matrixos-private-example.git")
MATRIXOS_PRIVATE_GIT_REPO_PATH=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "matrixOS" "PrivateGitRepoPath" "/etc/matrixos-private")
MATRIXOS_GIT_REPO=$(env_lib.get_simple_var "matrixOS" "GitRepo" "https://github.com/lxnay/matrixos.git")
MATRIXOS_DEFAULT_USERNAME=$(env_lib.get_simple_var "matrixOS" "DefaultUsername" "matrix")

# OSTree releasing and pulling.
MATRIXOS_OSTREE_REPO_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Ostree" "RepoDir" "ostree/repo")
MATRIXOS_OSTREE_REMOTE=$(env_lib.get_simple_var "Ostree" "Remote" "origin")
MATRIXOS_OSTREE_REMOTE_URL=$(env_lib.get_simple_var "Ostree" "RemoteUrl" "https://ostree.matrixos.org")
MATRIXOS_OSTREE_COLLECTION_ID=$(env_lib.get_simple_var "Ostree" "CollectionId" "org.matrixos.Main")
MATRIXOS_OSTREE_KEEP_OBJECTS_YOUNGER_THAN=$(env_lib.get_simple_var "Ostree" "KeepObjectsYoungerThan" "2 months")
MATRIXOS_OSTREE_FULL_SUFFIX=$(env_lib.get_simple_var "Ostree" "FullBranchSuffix" "full")

## Seeders section
MATRIXOS_SEEDER_DOWNLOADS_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Seeder" "DownloadsDir" "out/seeder/downloads")
MATRIXOS_SEEDER_DISTFILES_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Seeder" "DistfilesDir" "out/seeder/distfiles")
MATRIXOS_SEEDER_BINPKGS_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Seeder" "BinpkgsDir" "out/seeder/binpkgs")
MATRIXOS_SEEDER_PORTAGE_REPOS_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Seeder" "PortageReposDir" "out/seeder/repos")
MATRIXOS_SEEDER_GPG_KEYS_DIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Seeder" "GpgKeysDir" "out/seeder/gpg-keys")

# OSTree GPG Support.
MATRIXOS_OSTREE_GPG_ENABLED=$(env_lib.get_bool_var "Ostree" "Gpg" "true")
MATRIXOS_OSTREE_DEV_GPG_HOMEDIR=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Ostree" "DevGpgHomeDir" "out/ostree-gpg-private")
MATRIXOS_OSTREE_OFFICIAL_GPG_PUB_PATH=$(env_lib.get_root_var "${MATRIXOS_DEV_DIR}" "Ostree" "GpgOfficialPublicKey" "pubkeys/ostree-gpg/matrixos-pub.bin.gpg")

# /etc/matrixos-private derived configs.
MATRIXOS_OSTREE_GPG_KEY_PATH=$(env_lib.get_root_var "${MATRIXOS_PRIVATE_GIT_REPO_PATH}" "Ostree" "GpgPrivateKey" "ostree-gpg/keys/matrixos-priv.bin.key")
MATRIXOS_OSTREE_GPG_PUB_PATH=$(env_lib.get_root_var "${MATRIXOS_PRIVATE_GIT_REPO_PATH}" "Ostree" "GpgPublicKey" "ostree-gpg/keys/matrixos-pub.bin.gpg")
MATRIXOS_SECUREBOOT_KEY_PATH=$(env_lib.get_root_var "${MATRIXOS_PRIVATE_GIT_REPO_PATH}" "Seeder" "SecureBootPrivateKey" "secureboot/keys/db/db.key")
MATRIXOS_SECUREBOOT_CERT_PATH=$(env_lib.get_root_var "${MATRIXOS_PRIVATE_GIT_REPO_PATH}" "Seeder" "SecureBootPublicKey" "secureboot/keys/db/db.pem")
MATRIXOS_JAILBROKEN_BOOT_LOADER_ENTRY=$(env_lib.get_simple_var "Jailbreak" "BootLoaderEntry" "matrixos-jailbroken.conf")

MATRIXOS_RO_VDB=$(env_lib.get_simple_var "Releaser" "ReadOnlyVdb" "/usr/var-db-pkg")
MATRIXOS_OSTREE_SYSROOT=$(env_lib.get_simple_var "Ostree" "Sysroot" "/sysroot")
MATRIXOS_BOOT_ROOT=$(env_lib.get_simple_var "Imager" "BootRoot" "/boot")
MATRIXOS_EFI_ROOT=$(env_lib.get_simple_var "Imager" "EfiRoot" "/efi")
MATRIXOS_RELATIVE_EFI_BOOT_PATH=$(env_lib.get_simple_var "Imager" "RelativeEfiBootPath" "efi/BOOT")
MATRIXOS_BOOT_EFI_EXECUTABLE=$(env_lib.get_simple_var "Imager" "EfiExecutable" "BOOTX64.EFI")

MATRIXOS_EFI_STANDARD_BOOT_EXECUTABLE_PATH=$(env_lib.get_simple_var "Imager" "EfiStandardBootExecutablePath" '\EFI\BOOT\BOOTX64.EFI')

__MATRIXOS_ENV_PARSED=1
fi